User's Guide
------------

This part of the documentation will show you how to get started in using
Flask-Mixer.

.. toctree::
   :maxdepth: 2

   quickstart
   installation
   config

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api

Additional Notes
----------------

Bug tracker
~~~~~~~~~~~

If you have any suggestions, bug reports or
annoyances please report them to the issue tracker
at https://github.com/klen/Flask-Mixer/issues


Contributing
~~~~~~~~~~~~

Development of flask-mixer happens at github: https://github.com/klen/Flask-Mixer


Contributors
~~~~~~~~~~~~

* klen_ (Kirill Klenov)


License
~~~~~~~

Licensed under a `GNU lesser general public license`_.


.. _GNU lesser general public license: http://www.gnu.org/copyleft/lesser.html
.. _klen: http://klen.github.com/
